### ISSUE TITLE
PSKoans

### ISSUE THREAD

**Issue by hjorslev** [janikvonrotz/awesome-powershell#106]
In what section would it be fitting to place [PSKoans](https://github.com/vexx32/PSKoans)?

Or should we consider creating a new section named e.g. Learning Resources?

**Comment by janikvonrotz** [comment]
Interactive Learning or Learning Resources is a fitting option.

**Comment by hjorslev** [comment]
OK, I like Interactive Learning!

When adding this section I can see that the list is not alphabetical.

I am thinking of adjusting it alphabetically except for the Misc section which I'd suggest we keep in the bottom as it is now:

```md
* [API Wrapper](#api-wrapper)
* [Blogs](#blogs)
* [Books](#books)
* [Build Tools](#build-tools)
* [Code and Package Repositories](#code-and-package-repositories)
* [Commandline Productivity](#commandline-productivity)
* [Communities](#communities)
* [Documentation Helper](#documentation-helper)
* [Editors and IDEs](#editors-and-ides)
* [Frameworks](#frameworks)
* [Interactive Learning](#interactive-learning)
* [Module Development Templates](#module-development-templates)
* [Package Managers](#package-managers)
* [Parallel Processing](#parallel-processing)
* [Podcasts](#podcasts)
* [Security](#security)
* [SharePoint](#sharepoint)
* [SQL Server](#sql-server)
* [Testing](#testing)
* [Themes](#themes)
* [Videos](#videos)
* [Webserver](#webserver)
* [Misc](#misc)
```

**Comment by janikvonrotz** [comment]
I like the idea. Alphabeitcal order seems not to be a awesome list requirement, but why not.
