### ISSUE TITLE
Add community user groups to list

### ISSUE THREAD

**Issue by compwiz32** [janikvonrotz/awesome-powershell#125]
I run the biggest PowerShell user group in the US and I am also the community director for PowerShell.org / The Devops Collective. My group meets twice a month and has a YouTube channel containing three years of meeting content. We focus on PowerShell and automation. I am proud to say I have some of the most recognizable names in the community doing demos for our group. I'd love to get added to your list. 

**RTPSUG Content;**
https://www.meetup.com/Research-Triangle-PowerShell-Users-Group/
https://www.meetup.com/Research-Triangle-PowerShell-Users-Group/events/

**YouTube channel:**
www.youtube.com/rtpsug

**PowerShell.org Community Calendar**
I would also want to add some of the other user groups in community that are doing good work. Being the community director, I am up on which groups are providing good content regularly. we track user group events on powershell.org
https://powershell.org/calendar/

So why add this? I am not coming to you to solely pitch my group. Instead, I feel like the user community is not well represented and it a fantastic opportunity for people to learn about PowerShell and get exposed to new ideas and tools. My group is doing the best job of sharing with the community but the goal is help other groups get closer to level my group operates at.

**Comment by compwiz32** [comment]
er... i apologize... i see you have a communities section.. can i either be added tot he communities section ( i can submit a PR) or can we make a user  groups section? I am fine with either.

**Comment by janikvonrotz** [comment]
Hey there, thanks for the intro. I think your group is a great fit for the community section. Could you submit a PR?

**Comment by compwiz32** [comment]
Thank you! I'll get a PR in hopefully tonight or tomorrow.
