### ISSUE TITLE
Its not an issue but need help in sending outlook mail using powershell script

### ISSUE THREAD

**Issue by vishnuprakash9845** [janikvonrotz/awesome-powershell#129]
I am an automation engineer

I have have automated few test cases and getting the test results. This test results I wanted to forward to team using outlook using powershell. I tried many ways to do it, but not working. 

I want an powershell script to send outlook mail to people who I configure.

Can anyone please help me out in this.

**Comment by janikvonrotz** [comment]
Use `Send-MailMessage` to send mails with PowerShell
