### ISSUE TITLE
Add this list to https://github.com/sindresorhus/awesome

### ISSUE THREAD

**Issue by vors** [janikvonrotz/awesome-powershell#2]
Hello @janikvonrotz !

Would you like to make this list official and add it to the central place of awesome lists? :)

Regards,
-Sergei
PowerShell team

**Comment by janikvonrotz** [comment]
Sure! That would be great :+1:

**Comment by chantisnake** [comment]
according to the `awesome` contribution guide we need to have an awesome badge, a license, and contribution guidelines. I have got the badge ready in [my fork](https://github.com/chantisnake/awesome-powershell); I think we got a license now, so for now all we need is a contribution guide. then I can create a pr to the `awesome list`

**Comment by chantisnake** [comment]
okay, I see the contribution guide now... seems like I am going blind...

so as soon as you accepted my current pull request I will make a pull request to the `awesome list`

**Comment by chantisnake** [comment]
the pr is created: https://github.com/sindresorhus/awesome/pull/764

**Comment by daviwil** [comment]
I just tweeted this out so that we can hopefully get more folks contributing to the list before we re-submit the PR:

https://twitter.com/daviwil/status/776784098018766848

**Comment by chantisnake** [comment]
@daviwil that is a wonderful idea, since `awesome list` think we have too little stuff here (which is very true...)

**Comment by janikvonrotz** [comment]
Received great feedback, the list is growing fast.

**Comment by vors** [comment]
Should we re-send / re-open the PR again?
I think it's much better now.

**Comment by chantisnake** [comment]
I think resend the pr now would be appropriate.

**Comment by chantisnake** [comment]
see the feed back here: https://github.com/sindresorhus/awesome/pull/783

**Comment by vors** [comment]
I picked-up this work in https://github.com/sindresorhus/awesome/pull/820

**Comment by chantisnake** [comment]
thank you! @vors

**Comment by vors** [comment]
Done

**Comment by janikvonrotz** [comment]
Thank you all!
