### ISSUE TITLE
https://github.com/PowerShell/PowerShell should be in the list

### ISSUE THREAD

**Issue by vors** [janikvonrotz/awesome-powershell#22]
I think everybody would agree that https://github.com/PowerShell/PowerShell is awesome.
I spent 3 minutes thinking what's the right place to add it and it's hard to figure out.
It's related to my comment in https://github.com/janikvonrotz/awesome-powershell/issues/6#issuecomment-247813096

I'm leaving it as an open issue and a chance to rethink the structure and make it more loose.

**Comment by chantisnake** [comment]
I agree PowerShell is super awesome by any means, but I bet `Awesome Zsh` don't have `zsh` in their list, LOL

**Comment by janikvonrotz** [comment]
The Idea of adding `Powerhshell` itself to the list sounds reasonable to me. I suppose we simply add it to `Code and Package Repositories`.
