### ISSUE TITLE
Continuous Integration solution

### ISSUE THREAD

**Issue by lipkau** [janikvonrotz/awesome-powershell#63]
Are CI platforms worth adding to this repo?

* AppVeyor (Windows + Ubuntu agents)
* Travis (*nix + macOS agents)
* Azure DevOps (Windows + Ubuntu + macOS agents)
* TeamCity (build.powershell.org) (Windows agents - all powershell versions)

**Comment by janikvonrotz** [comment]
I would not consider these CI platform to be part of the PowerShell ecosystem.

**Comment by lipkau** [comment]
as you wish
