### ISSUE TITLE
Add PSPowerHour to the list?

### ISSUE THREAD

**Issue by chadmando** [janikvonrotz/awesome-powershell#64]
I have been watching the videos for the PSPowerHour.  Each hour is 5-6 short talks about some package or feature.  There is a GitHub repo with resources to accompany the video.  Some great insights and exposure for both the novice and the experienced PS user.  I was thinking of adding the GitHub link under the Communities section in a PR. Thoughts? 

https://github.com/PSPowerHour/PSPowerHour

**Comment by janikvonrotz** [comment]
The podcast section seems more suitable. I would welcome a PR!
