### ISSUE TITLE
Please consider adding...

### ISSUE THREAD

**Issue by mkellerman** [janikvonrotz/awesome-powershell#88]
Since you already have my PSTelegramAPI module, I figured you could add my PSTwitterAPI module as well ;)

And my Invoke-CommandAs module that allows you to run remote commands asSystem/asUser.

PSTwitterAPI: https://github.com/mkellerman/PSTwitterAPI
Invoke-CommandAs: https://github.com/mkellerman/Invoke-CommandAs

**Comment by janikvonrotz** [comment]
Hey there, could you file a PR for your submissions? Thanks.
