### ISSUE TITLE
GitHub Action to monitor markdown links

### ISSUE THREAD

**Issue by janikvonrotz** [janikvonrotz/awesome-powershell#90]
A while ago I wrote a [PS script to find dead links in my markdown files](https://janikvonrotz.ch/2019/11/11/find-dead-links-in-your-markdown-files/). Now I would like to integrate it as a GitHub Action. Once a week and for every PR the Action is triggered and throws an error if there are dead links. It must follow redirects and understand the HTTP return codes. The status of the workflow can be added as a badge to the readme.

Some challenges might be:

- Get a runner with pwsh
- Throttling of outgoing request
- Dealing with timeouts

Again the features:

- Find links in markdown files
- Request every link and follow redirects if required
- Report dead links as error and redirects as warnings
- Action is scheduled to run once a week and for every PR
-  Show workflow status as badge in readme

Optional:

- Create an issue for the dead links

If anybody is interested, let me know! I think it would be a nice excercice if you wanna know more about GitHub actions.

**Comment by janikvonrotz** [comment]
An GitHub Action has been added and needs refinement.

https://github.com/janikvonrotz/awesome-powershell/runs/563585962?check_suite_focus=true#step:3:146

**Comment by hjorslev** [comment]
I suggest that we rename the action from CI to _Quality Assurance_. Then that action has a job that is named _analyze-readme_ and finally, that job has one step named _Analyze Links_ as I have done here: https://github.com/hjorslev/awesome-powershell/runs/564121791?check_suite_focus=true

I have also made the output in the end of the step a little prettier with a summary of the dead links.

I am looking on how to create issue about the dead links (and to ensure that only one issue is created).

**Comment by janikvonrotz** [comment]
@hjorslev Thank you very much. Looks great!

Creating an issue might no be necessary after all. If the Readme is checked on each PR and a QA badge is added, that might be sufficent.

What do you think?

**Comment by hjorslev** [comment]
I think that makes sense -- at least for now we can test it and sees if it works with a QA badge. I have submitted a PR #99.

**Comment by janikvonrotz** [comment]
@hjorslev Thank you very much! It works perfectly.

**Comment by hjorslev** [comment]
You are welcome! Thanks for the feedback.
